function [ normDataMean1, normDataMean2, normDataMean3 ] = normalizeWeight( Weight, Day1, Day2, Day3 )
%Summary of normalizeWeight
%   This function serves to normalize the forces from each subject and then averages the normal
%   forces for the corresponding day input

normalizeWeightDataMatrix = [ Weight, Day1, Day2, Day3]; %Creates a matrix that will be used for weight and day data input
normData = zeros(25,1); %creates an array for the normalized forces

for i = 1:length(normalizeWeightDataMatrix) %Goes through the entirety of the matrix
    normData1(i) = (Day1(i)/Weight(i)); %normalizes the forces for the day by dividing the force generated by the subject's weight for the day input
end

for i = 1:length(normalizeWeightDataMatrix) %Goes through the entirety of the matrix
    normData2(i) = (Day2(i)/Weight(i)); %normalizes the forces for the day by dividing the force generated by the subject's weight for the day input
end

for i = 1:length(normalizeWeightDataMatrix) %Goes through the entirety of the matrix
    normData3(i) = (Day3(i)/Weight(i)); %normalizes the forces for the day by dividing the force generated by the subject's weight for the day input
end

normDataMean1 = mean(normData1); %Creates a mean normalized force from the normalized forces for the particular day.

normDataMean2 = mean(normData2); %Creates a mean normalized force from the normalized forces for the particular day.

normDataMean3 = mean(normData3); %Creates a mean normalized force from the normalized forces for the particular day.

end

